# Generated by Django 4.1.5 on 2023-02-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INA', 'Inactivo'), ('ACT', 'Activo')], max_length=3)),
                ('name', models.CharField(default='Test Event', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('BAN', 'Baneado'), ('INA', 'Inactivo')], default='ACT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembros', models.ManyToManyField(blank=True, to='eventos.persona')),
                ('nombre', models.CharField(default='Admin', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(choices=[(0, 'Admin'), (1, 'Bouncer'), (2, 'R.R.P.P.')])),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('RES', 'Reservada'), ('USA', 'Usada'), ('CAN', 'Cancelada')], max_length=3)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.usuario')),
                ('administrador', models.ManyToManyField(related_name='habilitadas', to='eventos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaInvitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('#008744', 'Green'), ('#0057e7', 'Blue'), ('#d62d20', 'Red'), ('#ffa700', 'Yellow'), ('#ffffff', 'White')], default='#0057e7', max_length=9)),
                ('administradores', models.ManyToManyField(blank=True, to='eventos.usuario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('nombre', models.CharField(default='Prueba', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Free',
            fields=[
                ('invitacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.invitacion')),
            ],
            bases=('eventos.invitacion',),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='lista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.listainvitados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listainvitados',
            name='personas',
            field=models.ManyToManyField(blank=True, through='eventos.Invitacion', to='eventos.persona'),
        ),
    ]
