# Generated by Django 4.1.5 on 2023-01-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('NOP', 'No Publicado'), ('PUB', 'Publicado'), ('ONG', 'Puertas Abiertas'), ('DON', 'Realizado'), ('CAN', 'Cancelado')], default='NOP', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='name',
            field=models.CharField(default='Test Event', max_length=100),
            preserve_default=False,
        ),
    ]
