# Generated by Django 4.1.5 on 2023-01-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_estado_evento_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('BAN', 'Baneado'), ('VIP', 'V.I.P.'), ('INA', 'Inactivo')], max_length=3)),
            ],
        ),
    ]
