# Generated by Django 4.1.5 on 2023-01-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.cliente'),
        ),
    ]
