# Generated by Django 4.1.5 on 2023-01-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_invitacion_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Persona',
        ),
    ]
