# Generated by Django 4.1.5 on 2023-01-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_rename_cliente_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitados', models.ManyToManyField(null=True, to='eventos.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.grupos')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.persona')),
            ],
        ),
    ]
