# Generated by Django 4.1.5 on 2023-01-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_grupos_membresia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupos',
            old_name='invitados',
            new_name='miembros',
        ),
        migrations.DeleteModel(
            name='Membresia',
        ),
    ]
