# Generated by Django 4.1.5 on 2023-01-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_rename_invitados_grupos_miembros_delete_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.persona'),
        ),
    ]
