# Generated by Django 4.1.5 on 2023-01-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_usuario_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='nombre',
            field=models.CharField(default='Admin', max_length=8),
            preserve_default=False,
        ),
    ]
