# Generated by Django 4.1.5 on 2023-01-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_grupos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activo'), ('BAN', 'Baneado'), ('INA', 'Inactivo')], max_length=3),
        ),
    ]
