# Generated by Django 4.1.5 on 2023-01-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_alter_persona_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='name',
            new_name='nombre',
        ),
    ]
