# Generated by Django 4.1.5 on 2023-01-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_rename_name_persona_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupos',
            new_name='Grupo',
        ),
    ]
