# Generated by Django 4.1.5 on 2023-01-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_rename_grupos_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitacion',
            old_name='usuario',
            new_name='vendedor',
        ),
        migrations.AddField(
            model_name='invitacion',
            name='administrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='habilitadas', to='eventos.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='miembros',
            field=models.ManyToManyField(blank=True, null=True, to='eventos.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activo'), ('BAN', 'Baneado'), ('INA', 'Inactivo')], default='ACT', max_length=3),
        ),
    ]
