# Generated by Django 4.1.5 on 2023-01-23 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_rename_usuario_invitacion_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaInvitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('#008744', 'Green'), ('#0057e7', 'Blue'), ('#d62d20', 'Red'), ('#ffa700', 'Yellow'), ('#ffffff', 'White')], default='#0057e7', max_length=9)),
                ('administradores', models.ManyToManyField(blank=True, null=True, to='eventos.usuario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('personas', models.ManyToManyField(blank=True, null=True, to='eventos.persona')),
            ],
        ),
    ]
