# Generated by Django 4.1.5 on 2023-01-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_listainvitados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listainvitados',
            name='administradores',
            field=models.ManyToManyField(blank=True, to='eventos.usuario'),
        ),
        migrations.AlterField(
            model_name='listainvitados',
            name='personas',
            field=models.ManyToManyField(blank=True, to='eventos.persona'),
        ),
    ]
