# Generated by Django 4.1.5 on 2023-01-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_alter_listainvitados_administradores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listainvitados',
            name='nombre',
            field=models.CharField(default='Prueba', max_length=15),
            preserve_default=False,
        ),
    ]
