# Generated by Django 4.1.5 on 2023-01-23 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_listainvitados_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('invitacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.invitacion')),
            ],
            bases=('eventos.invitacion',),
        ),
    ]
