# Generated by Django 4.1.5 on 2023-01-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='miembros',
            field=models.ManyToManyField(blank=True, to='eventos.persona'),
        ),
    ]
