# Generated by Django 4.1.5 on 2023-02-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial_squashed_0028_listainvitados_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.persona'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='listainvitados',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
    ]
