# Generated by Django 4.1.5 on 2023-02-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0029_invitacion_cliente_alter_evento_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listainvitados',
            name='evento',
        ),
    ]
