# Generated by Django 4.1.5 on 2023-02-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0030_remove_listainvitados_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free',
        ),
    ]
