# Generated by Django 4.1.5 on 2023-02-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_delete_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('RES', 'Reservada'), ('USA', 'Usada'), ('CAN', 'Cancelada')], max_length=3)),
                ('administrador', models.ManyToManyField(related_name='frees', to='eventos.usuario')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.persona')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.listainvitados')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.usuario')),
            ],
        ),
    ]
