# Generated by Django 4.1.5 on 2023-02-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitacion',
            name='administrador',
        ),
    ]
