# Generated by Django 4.1.5 on 2023-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0033_remove_invitacion_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listainvitados',
            name='color',
            field=models.CharField(choices=[('#008744', 'Green'), ('#0057e7', 'Blue'), ('#d62d20', 'Red'), ('#ffa700', 'Yellow')], default='#0057e7', max_length=9),
        ),
    ]
