# Generated by Django 4.1.5 on 2023-02-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0035_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
