# Generated by Django 4.1.5 on 2023-02-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0037_usuario_last_login_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
