# Generated by Django 4.1.5 on 2023-02-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0039_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
