# Generated by Django 4.1.5 on 2023-02-20 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0040_delete_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
