# Generated by Django 4.1.5 on 2023-02-25 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0044_alter_listainvitados_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
