# Generated by Django 4.1.5 on 2023-02-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0045_alter_invitacion_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
