# Generated by Django 4.1.5 on 2023-03-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0046_persona_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='listainvitados',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
