# Generated by Django 4.1.5 on 2023-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0047_listainvitados_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
