# Generated by Django 4.1.5 on 2023-03-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0050_alter_invitacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
    ]
