# Generated by Django 4.1.5 on 2023-03-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0051_remove_persona_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
