# Generated by Django 4.1.5 on 2023-03-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0052_alter_usuario_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Bouncer'), (2, 'R.R.P.P.'), (3, 'Guest')], null=True),
        ),
    ]
