# Generated by Django 4.1.5 on 2023-03-03 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0053_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.persona'),
        ),
        migrations.AlterField(
            model_name='free',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='free',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.listainvitados'),
        ),
        migrations.AlterField(
            model_name='free',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.persona'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.listainvitados'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
