# Generated by Django 4.1.5 on 2023-03-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0054_alter_free_cliente_alter_free_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
    ]
