# Generated by Django 4.1.5 on 2023-03-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0055_alter_free_evento_alter_invitacion_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
