# Generated by Django 4.1.7 on 2023-07-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('eventos', '0058_invitacion_eventos_inv_evento__37828e_idx'), ('eventos', '0059_remove_invitacion_eventos_inv_evento__37828e_idx_and_more'), ('eventos', '0060_free_eventos_fre_evento__3ca6c3_idx'), ('eventos', '0061_persona_eventos_per_estado_a9e59c_idx')]

    dependencies = [
        ('eventos', '0057_historicalusuario_historicalpersona_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitacion',
            index=models.Index(fields=['evento', 'cliente', 'vendedor'], name='eventos_inv_evento__37828e_idx'),
        ),
        migrations.RemoveIndex(
            model_name='invitacion',
            name='eventos_inv_evento__37828e_idx',
        ),
        migrations.AddIndex(
            model_name='invitacion',
            index=models.Index(fields=['evento', 'cliente', 'vendedor', 'estado'], name='eventos_inv_evento__5dc332_idx'),
        ),
        migrations.AddIndex(
            model_name='free',
            index=models.Index(fields=['evento', 'cliente', 'vendedor', 'estado'], name='eventos_fre_evento__3ca6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['estado'], name='eventos_per_estado_a9e59c_idx'),
        ),
    ]
